# Use awesome bot to verify that all URLs in the README are valid.

name: README URL Checker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Ruby
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake

    - name: Install Awesome Bot
      run: gem install awesome_bot
    - name: Run Awesome Bot
      run: |
        awesome_bot README.md --allow-dupe --allow-redirect
        echo "If this workflow fails, it usually means there's a broken link in the README that needs fixing. This workflow has been flaky in the past, so verify the reported broken links, but don't sweat it if this workflow is broken."
